# Generated by Django 5.2.3 on 2025-06-25 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('acompanante', 'Acompañante'), ('externo', 'Externo')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(choices=[('conductor', 'Conductor'), ('supervisor', 'Supervisor'), ('mantenimiento', 'Mantenimiento'), ('administrativo', 'Administrativo')], max_length=14)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('nocturno', 'Nocturno'), ('mixto', 'Mixto')], max_length=10)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('punto_inicio', models.CharField(max_length=100)),
                ('punto_final', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tiempo_estimado', models.DurationField()),
                ('activo', models.BooleanField(default=True)),
                ('autobus_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.autobus')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('dias_disponibles', models.JSONField()),
                ('capacidad_disponible', models.PositiveIntegerField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='autobus',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'puesto': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trabajador'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('contrasena_hash', models.CharField(max_length=128)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_conexion', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='core.persona')),
            ],
        ),
        migrations.AddField(
            model_name='trabajador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trabajador', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reservacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_viaje', models.DateField()),
                ('asiento_numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='reservado', max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.autobus')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horario')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='core.usuario')),
            ],
            options={
                'unique_together': {('autobus', 'fecha_viaje', 'asiento_numero', 'horario')},
            },
        ),
    ]
